/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PriceQuote {
  'currentPrice' : number,
  'ticker' : string,
  'dailyChange' : number,
  'previousClose' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  /**
   * / Add stock to user's favorites list.
   */
  'addFavorite' : ActorMethod<[string], undefined>,
  /**
   * / Get user's favorite stocks.
   */
  'getFavorites' : ActorMethod<[], Array<[string, bigint]>>,
  /**
   * / Fetch multiple stock tickers for comparison.
   */
  'getMultipleStocks' : ActorMethod<[Array<string>, string], Array<string>>,
  /**
   * / Fetch current price quote data.
   */
  'getPriceQuote' : ActorMethod<[string], PriceQuote>,
  /**
   * / Fetch OHLCV data from Yahoo Finance API with caching.
   */
  'getStockData' : ActorMethod<[string, string], string>,
  /**
   * / Transform function to handle HTTP outcall responses.
   */
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];